### ISSUE TITLE
[🔷 Feature request ] Share the code of "San-Francisco house prices predictions live demo"

### ISSUE THREAD

**Issue by 404-html** [matiasvlevi/Dann#19]
### Feature
It would be nice to have the code of "San-Francisco house prices predictions live demo" and maybe explained in detail?

### Type
- [ ] Dann
- [ ] Matrix
- [ ] Layer
- [ ] Activation functions
- [ ] Loss functions
- [ ] Pool functions
- [ ] Datasets
- [ ] Documentation
- [x] tests & examples
- [ ] Other

**Comment by matiasvlevi** [comment]
Hey 404,

I updated the code, added some descriptive comments & made it public!
Check it out [here](https://github.com/matiasvlevi/Dannjs-San-Francisco)
