### ISSUE TITLE
[🔺 BUG ]: Grunt error | npm ERR! code ELIFECYCLE errno3 

### ISSUE THREAD

**Issue by matiasvlevi** [matiasvlevi/Dann#28]
We are getting errors with `npm run test` and `npm run build` 

`npm run test`:
![image](https://user-images.githubusercontent.com/55809005/123524399-d7233700-d6eb-11eb-8d96-beaaaa162929.png)

`npm run build`:
![image](https://user-images.githubusercontent.com/55809005/123524435-089c0280-d6ec-11eb-8c3f-8164cf713c46.png)

I am not sure why this is happening. I am using node 14.17.1 by the way, in windows.

_Originally posted by @Labnann in https://github.com/matiasvlevi/Dann/issues/22#issuecomment-869055913_

**Comment by Labnann** [comment]
I am providing the full screenshot of this occurance.
![image](https://user-images.githubusercontent.com/55809005/123533457-96e9a600-d737-11eb-9580-333096afe6cb.png)

**Comment by matiasvlevi** [comment]
Looks like `@babel/core` is not installed, I just commited the `package.json` with it installed. 
You can install it with `npm install @babel/core --save-dev`. Let me know if this works.

**Comment by Labnann** [comment]
I insitalled @babel/core. Then I ran `npm run test`, 
I got the same error but with:
`>> Error: Cannot find module 'mocha'`
Then I installed mocha: `npm install mocha --save-dev`. After that it showed:
`>> Error: Cannot find module 'terser'`
`Warning: Cannot find module 'prettier'`

After installing these two:  I have this now.

![image](https://user-images.githubusercontent.com/55809005/123534036-d6b28c80-d73b-11eb-8da4-2b63446ce2b6.png)

**Comment by matiasvlevi** [comment]
I'm going to add these dependencies in `package.json`, it must have worked on my computer because of global modules.
The error I see in the screenshot is not a dependency issue, its something I can fix in the tasks I'm working on it.

**Comment by matiasvlevi** [comment]
I'm going to add these dependencies in `package.json`, it must have worked on my computer because of global modules.
The error I see in the screenshot is not a dependency issue, its something I just fixed in the gruntfile.

**Comment by Labnann** [comment]
Nice. `npm run test` is working now.
`npm run build` was failing with this error:
![image](https://user-images.githubusercontent.com/55809005/123539325-01f8a400-d75b-11eb-9af0-c63fcbf381c6.png)

However, after running `npm run test` for the first time, `npm run build` started working correctly too. 

![image](https://user-images.githubusercontent.com/55809005/123539392-569c1f00-d75b-11eb-97f6-c9d6f189c72a.png)

I have checked `npm run final` too. It is working well.

So I think my testing brunch is ok now. I will create a pull request from it for you. You can merge them if you think everything is ok there.

**Comment by matiasvlevi** [comment]
Perfect! I'll look into the whole `test` before `build` thing, this is an error with grunt tasks. 
I also on question, have you pushed your repo after `npm run final` or before?

Other than that I'm merging your branch!
