### ISSUE TITLE
[🔷 Feature request ]: numToString, reverse from stringToNum.

### ISSUE THREAD

**Issue by matiasvlevi** [matiasvlevi/Dann#32]
### Feature
A static function that takes in an array of values and returns a string. Just like `Rann.stringToNum` reversed. This method should be added to the [RNN branch](https://github.com/matiasvlevi/Dann/tree/RNN).

### Type
- [ ] Dann
- [ ] Matrix
- [ ] Layer
- [x] Rann
- [ ] Activation functions
- [ ] Loss functions
- [ ] Pool functions
- [ ] Datasets
- [ ] Documentation
- [ ] tests & examples
- [ ] Other 

### Examples
Existing stringToNum method
```js
Rann.stringToNum('hey');
// Returns [0.7604166666666666, 0.7291666666666666, 0.9375]
```
numToString method
```js
Rann.numToString([0.7604166666666666, 0.7291666666666666, 0.9375]);
// Should return 'hey'
```

<br/>

**Additional context**
Be sure to commit changes to the  [RNN branch](https://github.com/matiasvlevi/Dann/tree/RNN).

**Comment by ramos-papadopoulos** [comment]
I’ll do it
