### ISSUE TITLE
[🔷 Feature request ]: Sin wave dataset for Rann 

### ISSUE THREAD

**Issue by matiasvlevi** [matiasvlevi/Dann#37]
### Feature
Segmented Sin wave dataset for Rann. 

### Type
- [ ] Dann
- [ ] Matrix
- [ ] Layer
- [ ] Activation functions
- [ ] Loss functions
- [ ] Pool functions
- [x] Datasets
- [ ] Documentation
- [ ] tests & examples
- [ ] Other 

### Description
Just like we have XOR & Binary digit testing datasets for Dann models, it would be nice to have a testing dataset for the upcoming Rann model. The changes would have to be applied to `origin/RNN` branch. The method creating the dataset should be referenced in the `module.exports` in `src/io/exports.js`.

The source file for this method should be in `src/core/datasets/`

### Context
We train a Rann model this way. We feed an array of sequences to the Rann model. The sequences lengths must be the same as the number of input neurons the Rann model has.
```js
rnn.train([
  [0, 1],
  [2, 3],
  [4, 5]
]);
```
We could technically have a sin wave in an array of sequences to later train a model with.
```js
let data = [
  [0, sinus values..., ],
  [sinus values continuation..., ],
  [sinus values continuation..., ],
  [sinus values continuation..., ],
]
```

### Example
Here is an example of how the method could work.
```js
let dataset = makeSinWave( sequence_length, total_length, resolution );
console.log(dataset);
```

**Comment by SharkAce** [comment]
I'm on it

**Comment by matiasvlevi** [comment]
Just merged, thanks!
