### ISSUE TITLE
[🔶 Change request ]: Activations should be case insensitive

### ISSUE THREAD

**Issue by matiasvlevi** [matiasvlevi/Dann#44]
### Change
We could use `toLocaleLowerCase` to specify the activations functions without worrying about capitalization.

### Type
- [x] Dann
- [ ] Matrix
- [x] Layer
- [x] Activation functions
- [ ] Loss functions
- [ ] Pool functions
- [ ] Datasets
- [ ] Documentation
- [ ] tests & examples
- [ ] Other 

### Examples

these statements would all be valid if we ignore capitalization.
```js
nn.addHiddenLayer(x, 'leakyrelu');
nn.addHiddenLayer(x, 'LEAKYRELU');
nn.addHiddenLayer(x, 'leakyReLU');
```

**Additional context**

This also means all activation names need to be in lowercase, and when we add a new activation with `Add.activation`, we should also convert the input name to lowercase.

Changes should be in these methods: 

* `Layer.stringToFunc` parses the activation names into an object containing, the derivative & the activation.
* `Add.activation` adds new activations, and also needs to respect the case insensitivity.
* Other `Dann` methods using activation strings will need some minor adjusments.

**Comment by and1can** [comment]
Hi @matiasvlevi , 

I have been looking into this issue. Is it okay if I work on this?

**Comment by matiasvlevi** [comment]
Yep it is! I am assigning you to this issue.
